/**
 * ❌ BAD EXAMPLE: Broken Theme Generation
 * Study every violation. Do NOT produce output like this.
 *
 * VIOLATIONS IN THIS FILE:
 * ❌ [TOK] Raw hex throughout — the whole point of a generator is a space you can reason about
 * ❌ [TOK] Ramp generated by stepping HSL lightness — the steps are perceptually uneven
 * ❌ [COLOR] Hue rotated in HSL, where equal rotations produce unequal apparent brightness
 * ❌ [COLOR] Constant saturation across the ramp — neon at the light end, mud at the dark end
 * ❌ [COLOR] No gamut clamping, so out-of-range colours silently clip to the same rendered value
 * ❌ [A11Y] Contrast never computed — the surface/text pair ships unmeasured
 * ❌ [A11Y] Status conveyed by colour alone: a red or green dot with no label, icon or text
 * ❌ [MOTION] 300ms colour transition on the theme switch — reads as a rendering fault
 * ❌ [MOTION] transition-all — animates every property, including layout ones
 * ❌ [STATE] Persists a resolved `isDark` boolean, so "follow the system" is silently lost
 * ❌ [STATE] localStorage read without try/catch — throws in Safari private mode
 * ❌ [RES] min-h-screen instead of min-h-[100dvh]
 * ❌ [TYP] Roboto as the display face — banned
 * ❌ [COPY] Placeholder copy ("Lorem ipsum")
 * ❌ [TS] `any` props, no exported interface
 */

import { useEffect, useState } from "react";

// HSL ramp: same declared lightness, wildly different perceived brightness per hue.
function badRamp(hue: number): string[] {
  return [95, 80, 65, 50, 35, 20].map((l) => `hsl(${hue}, 80%, ${l}%)`);
}

export default function BadHexTheme({ hue = 248 }: any) {
  // A boolean, so a user who picked "auto" is pinned the first time the system flips.
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    // Unguarded: this throws in Safari private mode and takes the component with it.
    const stored = localStorage.getItem("isDark");
    setIsDark(stored === "true");
  }, []);

  const ramp = badRamp(hue);

  return (
    <div
      className="min-h-screen font-[Roboto,sans-serif] transition-all duration-300"
      style={{ background: isDark ? "#0d0d12" : "#ffffff", color: isDark ? "#f2f2f2" : "#111111" }}
    >
      {/* ❌ hex straight into the token layer — no OKLCH space to reason in */}
      <style>{`
        :root { --background: #ffffff; --foreground: #111111; --font-sans: "Roboto", sans-serif; }
        @theme inline { --color-accent: #4f46e5; }
      `}</style>
      <h1 className="text-3xl" style={{ color: "#4f46e5" }}>
        Lorem ipsum theme
      </h1>

      <button
        onClick={() => {
          setIsDark(!isDark);
          localStorage.setItem("isDark", String(!isDark));
        }}
        style={{ background: "#4f46e5", color: "#ffffff", height: 28 }}
      >
        Toggle
      </button>

      <div className="flex">
        {ramp.map((c) => (
          <div key={c} style={{ background: c, width: 48, height: 48 }} />
        ))}
      </div>

      {/* Status by colour alone. Nothing here says what the dot means. */}
      <span style={{ display: "inline-block", width: 10, height: 10, borderRadius: 5, background: "#22c55e" }} />
      <span style={{ display: "inline-block", width: 10, height: 10, borderRadius: 5, background: "#ef4444" }} />

      <p style={{ color: "#9ca3af" }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>
  );
}
